### ISSUE TITLE
可以训练自己的dataset吗？

### ISSUE THREAD

**Issue by YohannJin** [calmisential/DeepLearning.pytorch#1]
你好问一下可以训练自己的voc训练集吗

**Comment by calmisential** [comment]
可以，你只需要修改[dataset_cfg.py](https://github.com/calmisential/DeepLearning.pytorch/blob/main/configs/dataset_cfg.py)中的相关参数即可

**Comment by YohannJin** [comment]
谢谢

**Comment by YohannJin** [comment]
evaluate.py可以使用吗？有图片尺寸限制吗

**Comment by calmisential** [comment]
> evaluate.py可以使用吗？有图片尺寸限制吗

可以用，输入网络的图片大小都会被自动resize

**Comment by YohannJin** [comment]
是可以用512ssd的模型进行evaluation吗？

**Comment by calmisential** [comment]
> 是可以用512ssd的模型进行evaluation吗？

对，不过你需要先训练好模型

**Comment by YohannJin** [comment]
好的，谢谢
